### PR TITLE
ci(oci): attempt to push using only registry/namespace

### PR DESCRIPTION
**Pull request by andrewazores**
See #175 #174 #173

### CODE REVIEW

**Comment by tthvo** [comment]
We might clash with https://github.com/cryostatio/cryostat-legacy/pkgs/container/cryostat?

**Comment by andrewazores** [comment]
Yea, that's what happens: https://github.com/cryostatio/cryostat-legacy/pkgs/container/cryostat

Need some way to get the chart releaser to package the chart with `cryostat-helm` as its name, not just `cryostat`.

**Comment by andrewazores** [comment]
Or actually, I guess it's `helm push` which is giving us problems, not the chart releaser.

**Comment by tthvo** [comment]
The chart releaser is also having issue I think since the release still got published. Can we just use `helm package`?

**Comment by andrewazores** [comment]
Maybe we can just hack it by patching the `charts/cryostat/Chart.yaml` to set `name: cryostat-helm` within the CI run...

**Comment by tthvo** [comment]
https://trstringer.com/helm-charts-github-container-registry/

**Comment by tthvo** [comment]
> Maybe we can just hack it by patching the charts/cryostat/Chart.yaml to set name: cryostat-helm within the CI run...

That sounds reasonable to me :D

**Comment by tthvo** [comment]
Also, I figured out the `skip_upload`. Seems like it is only available on `main`, not latest `1.6.0` :D

**Pull request merged**
