### PR TITLE
fix(urls): use relative Grafana ext url, remove unused storage ext url

### PR DESCRIPTION
**Pull request by andrewazores**
- **fix(storage): remove unused STORAGE_EXT_URL env var**
- **use relative grafana dashboard ext url**
- **update post-install notes**

See https://github.com/cryostatio/cryostat-operator/pull/874

### CODE REVIEW

**Review by ebaron — COMMENTED** [review]
Do we also need the Grafana 9 fixes in Helm?

**Comment by andrewazores** [comment]
Yes I suppose so

**Comment by andrewazores** [comment]
#147

**Review by ebaron — COMMENTED** [review]
I think we still need the ROUTE_HOST part for NOTES.txt

> $ helm install cryostat ./charts/cryostat/ --set core.route.enabled=true,authentication.openshift.enabled=true
> NAME: cryostat
> LAST DEPLOYED: Fri Jun  7 16:44:23 2024
> NAMESPACE: helm-test
> STATUS: deployed
> REVISION: 1
> NOTES:
> 1. Tell Cryostat how to serve external traffic:
>   ```
>   No actions required with this configuration.
>   ```
> 
> 2. Visit the Cryostat application at: 
>   ```
>   echo https://$ROUTE_HOST
>   ```
> $   echo https://$ROUTE_HOST
> https://

**Review by ebaron — APPROVED** [review]

**Pull request merged**
