### PR TITLE
chore(release): prepare 2.4.0 release

### PR DESCRIPTION
**Pull request by andrewazores**
Related to cryostatio/cryostat#1695

### CODE REVIEW

**Comment by andrewazores** [comment]
Screenshot_2023-12-07_16-28-26

Weird CI failure - it's trying to download a tool and getting an Unauthorized response.

**Comment by andrewazores** [comment]
Judging by the [release notes](https://github.com/helm/chart-testing-action/releases) on that `helm/chart-testing-action`, maybe we should look at upgrading from 2.4.0.

**Comment by andrewazores** [comment]
https://github.com/helm/chart-testing-action/issues/132

Upgrading that action should indeed fix it. I'll open a PR.

**Review by ebaron — APPROVED** [review]

**Comment by andrewazores** [comment]
Not sure why the CI is hanging now.

**Comment by andrewazores** [comment]
It eventually timed out.

https://github.com/cryostatio/cryostat-helm/actions/runs/7134459037/job/19429320884

```
==> Logs of container cryostat-2p4s2u67uj-54b5d78696-nstxt
------------------------------------------------------------------------------------------------------------------------
INFO exec -a "java" java -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -XX:-ExitOnOutOfMemoryError -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -cp "." -jar /deployments/quarkus-run.jar 
INFO running in /deployments
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-12-07 22:04:35,229 INFO  [io.quarkus] (main) jfr-datasource 2.4.0 on JVM (powered by Quarkus 3.2.4.Final) started in 1.447s. Listening on: http://0.0.0.0:8080/
2023-12-07 22:04:35,295 INFO  [io.quarkus] (main) Profile prod activated. 
2023-12-07 22:04:35,295 INFO  [io.quarkus] (main) Installed features: [cdi, reactive-routes, smallrye-context-propagation, vertx]
------------------------------------------------------------------------------------------------------------------------
<== Logs of container cryostat-2p4s2u67uj-54b5d78696-nstxt
------------------------------------------------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> Description of pod cryostat-2p4s2u67uj-test-connection
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Name:             cryostat-2p4s2u67uj-test-connection
Namespace:        helm-test
Priority:         0
Service Account:  default
Node:             ci-7134459037-control-plane/172.18.0.2
Start Time:       Thu, 07 Dec 2023 22:04:41 +0000
Labels:           app.kubernetes.io/instance=cryostat-2p4s2u67uj
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=cryostat
                  app.kubernetes.io/version=2.4.0
                  helm.sh/chart=cryostat-0.4.0
Annotations:      helm.sh/hook: test
Status:           Running
IP:               10.244.0.15
IPs:
  IP:  10.244.0.15
Containers:
  curl:
    Container ID:  containerd://8d8104e3bad10ee8c43df60f4acf3ceb5ef1b9dd1ab678902d74f371687ea4ae
    Image:         registry.access.redhat.com/ubi8/ubi:latest
    Image ID:      registry.access.redhat.com/ubi8/ubi@sha256:449da7f8f2ef6285a8445a1e31af57a97b9dae5dcf009b1629c59742c89c68c3
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -ec
      dnf install --disableplugin=subscription-manager -yq jq; curl -sSf --retry 10 --retry-connrefused -o /tmp/out.json http://cryostat-2p4s2u67uj:8181/health; cat /tmp/out.json; jq -e '(.cryostatVersion | test("^v'2.4.0'")) and .datasourceAvailable == true' /tmp/out.json; curl -sSf --retry 10 --retry-connrefused http://cryostat-2p4s2u67uj-grafana:3000/api/health
      
    State:          Running
      Started:      Thu, 07 Dec 2023 22:04:42 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9ckpf (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  kube-api-access-9ckpf:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  10m   default-scheduler  Successfully assigned helm-test/cryostat-2p4s2u67uj-test-connection to ci-7134459037-control-plane
  Normal  Pulling    10m   kubelet            Pulling image "registry.access.redhat.com/ubi8/ubi:latest"
  Normal  Pulled     10m   kubelet            Successfully pulled image "registry.access.redhat.com/ubi8/ubi:latest" in 389.054561ms (389.078576ms including waiting)
  Normal  Created    10m   kubelet            Created container curl
  Normal  Started    10m   kubelet            Started container curl
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<== Description of pod cryostat-2p4s2u67uj-test-connection
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
------------------------------------------------------------------------------------------------------------------------
==> Logs of container cryostat-2p4s2u67uj-test-connection
------------------------------------------------------------------------------------------------------------------------

Installed:
  jq-1.6-7.el8.x86_64                oniguruma-6.8.2-2.el8.x86_64               

{"dashboardAvailable":false,"datasourceConfigured":true,"reportsConfigured":false,"reportsAvailable":true,"dashboardConfigured":false,"cryostatVersion":"v2.4.0-0-gaefd7131","datasourceAvailable":true}true
------------------------------------------------------------------------------------------------------------------------
<== Logs of container cryostat-2p4s2u67uj-test-connection
------------------------------------------------------------------------------------------------------------------------
========================================================================================================================
Deleting release "cryostat-2p4s2u67uj"...
release "cryostat-2p4s2u67uj" uninstalled
Error: failed installing charts: failed processing charts

------------------------------------------------------------------------------------------------------------------------
 ✖︎ cryostat => (version: "0.4.0", path: "charts/cryostat") > failed waiting for process: exit status 1
------------------------------------------------------------------------------------------------------------------------
failed installing charts: failed processing charts
Error: Process completed with exit code 1.
```

**Comment by ebaron** [comment]
It worked on a retry, maybe an infra issue.

**Comment by tthvo** [comment]
Tested locally seemed to also work.

```bash
$ podman run -it --network host --workdir=/data \
--volume ~/.kube/config:/root/.kube/config:ro \
--volume $(pwd):/data quay.io/helmpack/chart-testing:latest

/data# ct install --target-branch cryostat-v2.4 --upgrade --namespace=helm-test --config ct.yaml            
...output-omitted...
------------------------------------------------------------------------------------------------------------------------
 ✔︎ cryostat => (version: "0.4.0", path: "charts/cryostat")
------------------------------------------------------------------------------------------------------------------------
All charts installed successfully
/data # 
```

**Pull request merged**
